var subType = this.getField("ItemSubType");
var enchantmentType1 = this.getField("Enchantment 1");
var enchantmentType2 = this.getField("Enchantment 2");
var enchantmentType3 = this.getField("Enchantment 3");
var itemName = this.getField("Name1");

// values: prefix/suffix, name, description, rarity, attunement
var armorTypes = ["-Seletct Armor-", "Helmet", "Shield", "Breastplate", "Leather Armor", "Amulet"]
var armorEnchantment1 = ["1st Enchantment",
  ["Absorption", "0--Absorption--When you take acid, cold, fire, lightning, or thunder damage while wearing this armor, you can choose to take no damage instead. Once used, this property can’t be used again until the next dawn.--1--1--When you take acid, cold, fire, lightning, or thunder damage while wearing this armor, you can choose to take no damage instead. You gain temporary hit points equal to half the damage prevented this way (rounded down). Once used, this property can’t be used again until the next dawn."],
  ["Adamantine", "1--Adamantine--While wearing this armor, any critical hit against you becomes a normal hit.--4--0--While wearing this armor, bludgeoning, piercing, and slashing damage that you take from nonmagical weapons is reduced by 3. In addition, any critical hit against you becomes a normal hit."],
  ["Agathys", "0--Agathys--While wearing this armor, you can use an action to cast armor of Agathys. Once used, this property can’t be used again until the next dawn.--2--1--This armor has 3 charges. While wearing it, you can use an action and expend 1 or more of its charges to cast armor of Agathys. For 1 charge, you cast the 1st-level version of the spell. You can increase the spell slot level by one for each additional charge you expend. You can also use an action and expend 2 charges to cast the cold version of fire shield. The armor regains all expended charges daily at dawn."],
  ["Animation", "0--Animation--While holding this magic shield, you can speak its command word as a bonus action to cause it to animate. The shield leaps into the air and hovers vertically in your space to protect you as if you were wielding it, leaving your hands free. The shield remains animated for 1 minute, until you use a bonus action to end this effect, or until you are incapacitated or die, at which point the shield falls to the ground or into your hand if you have one free. Once used, this property can’t be used again until the next dawn.--2--1--This magic shield has 3 charges. While holding it, you can speak its command word as a bonus action and expend 1 of its charges to cause it to animate. The shield leaps into the air and hovers vertically in your space to protect you as if you were wielding it, leaving your hands free. The shield remains animated for 1 minute, until you use a bonus action to end this effect, or until you are incapacitated or die, at which point the shield falls to the ground or into your hand if you have one free. The shield regains all expended charges daily at dawn."],
  ["Antimagic", "0--Antimagic--While wearing this armor, you can use an action to surround yourself with a 10-foot-radius invisible sphere of antimagic, as if you had cast the spell antimagic field. This effect lasts until the end of your next turn. Once used, this property can’t be used again until the next dawn.--2--1--This armor has 3 charges. While wearing it, you can use an action and expend 1 of its charges to surround yourself with a 10-foot-radius invisible sphere of antimagic, as if you had cast the spell antimagic field. This effect lasts until the end of your next turn. While this antimagic field is active, you can use a bonus action and expend 1 of the armor’s charges to extend its duration until the end of your next turn. The armor regains all expended charges daily at dawn."]
]
var armorEnchantment2 = ["2nd Enchantment",
  ["Absorption", "0--Absorption--When you take acid, cold, fire, lightning, or thunder damage while wearing this armor, you can choose to take no damage instead. Once used, this property can’t be used again until the next dawn.--1--1--When you take acid, cold, fire, lightning, or thunder damage while wearing this armor, you can choose to take no damage instead. You gain temporary hit points equal to half the damage prevented this way (rounded down). Once used, this property can’t be used again until the next dawn."],
  ["Adamantine", "1--Adamantine--While wearing this armor, any critical hit against you becomes a normal hit.--4--0--While wearing this armor, bludgeoning, piercing, and slashing damage that you take from nonmagical weapons is reduced by 3. In addition, any critical hit against you becomes a normal hit."],
  ["Agathys", "0--Agathys--While wearing this armor, you can use an action to cast armor of Agathys. Once used, this property can’t be used again until the next dawn.--2--1--This armor has 3 charges. While wearing it, you can use an action and expend 1 or more of its charges to cast armor of Agathys. For 1 charge, you cast the 1st-level version of the spell. You can increase the spell slot level by one for each additional charge you expend. You can also use an action and expend 2 charges to cast the cold version of fire shield. The armor regains all expended charges daily at dawn."],
  ["Animation", "0--Animation--While holding this magic shield, you can speak its command word as a bonus action to cause it to animate. The shield leaps into the air and hovers vertically in your space to protect you as if you were wielding it, leaving your hands free. The shield remains animated for 1 minute, until you use a bonus action to end this effect, or until you are incapacitated or die, at which point the shield falls to the ground or into your hand if you have one free. Once used, this property can’t be used again until the next dawn.--2--1--This magic shield has 3 charges. While holding it, you can speak its command word as a bonus action and expend 1 of its charges to cause it to animate. The shield leaps into the air and hovers vertically in your space to protect you as if you were wielding it, leaving your hands free. The shield remains animated for 1 minute, until you use a bonus action to end this effect, or until you are incapacitated or die, at which point the shield falls to the ground or into your hand if you have one free. The shield regains all expended charges daily at dawn."],
  ["Antimagic", "0--Antimagic--While wearing this armor, you can use an action to surround yourself with a 10-foot-radius invisible sphere of antimagic, as if you had cast the spell antimagic field. This effect lasts until the end of your next turn. Once used, this property can’t be used again until the next dawn.--2--1--This armor has 3 charges. While wearing it, you can use an action and expend 1 of its charges to surround yourself with a 10-foot-radius invisible sphere of antimagic, as if you had cast the spell antimagic field. This effect lasts until the end of your next turn. While this antimagic field is active, you can use a bonus action and expend 1 of the armor’s charges to extend its duration until the end of your next turn. The armor regains all expended charges daily at dawn."]
]
var armorEnchantment3 = ["3rd Enchantment",
  ["Absorption", "0--Absorption--When you take acid, cold, fire, lightning, or thunder damage while wearing this armor, you can choose to take no damage instead. Once used, this property can’t be used again until the next dawn.--1--1--When you take acid, cold, fire, lightning, or thunder damage while wearing this armor, you can choose to take no damage instead. You gain temporary hit points equal to half the damage prevented this way (rounded down). Once used, this property can’t be used again until the next dawn."],
  ["Adamantine", "1--Adamantine--While wearing this armor, any critical hit against you becomes a normal hit.--4--0--While wearing this armor, bludgeoning, piercing, and slashing damage that you take from nonmagical weapons is reduced by 3. In addition, any critical hit against you becomes a normal hit."],
  ["Agathys", "0--Agathys--While wearing this armor, you can use an action to cast armor of Agathys. Once used, this property can’t be used again until the next dawn.--2--1--This armor has 3 charges. While wearing it, you can use an action and expend 1 or more of its charges to cast armor of Agathys. For 1 charge, you cast the 1st-level version of the spell. You can increase the spell slot level by one for each additional charge you expend. You can also use an action and expend 2 charges to cast the cold version of fire shield. The armor regains all expended charges daily at dawn."],
  ["Animation", "0--Animation--While holding this magic shield, you can speak its command word as a bonus action to cause it to animate. The shield leaps into the air and hovers vertically in your space to protect you as if you were wielding it, leaving your hands free. The shield remains animated for 1 minute, until you use a bonus action to end this effect, or until you are incapacitated or die, at which point the shield falls to the ground or into your hand if you have one free. Once used, this property can’t be used again until the next dawn.--2--1--This magic shield has 3 charges. While holding it, you can speak its command word as a bonus action and expend 1 of its charges to cause it to animate. The shield leaps into the air and hovers vertically in your space to protect you as if you were wielding it, leaving your hands free. The shield remains animated for 1 minute, until you use a bonus action to end this effect, or until you are incapacitated or die, at which point the shield falls to the ground or into your hand if you have one free. The shield regains all expended charges daily at dawn."],
  ["Antimagic", "0--Antimagic--While wearing this armor, you can use an action to surround yourself with a 10-foot-radius invisible sphere of antimagic, as if you had cast the spell antimagic field. This effect lasts until the end of your next turn. Once used, this property can’t be used again until the next dawn.--2--1--This armor has 3 charges. While wearing it, you can use an action and expend 1 of its charges to surround yourself with a 10-foot-radius invisible sphere of antimagic, as if you had cast the spell antimagic field. This effect lasts until the end of your next turn. While this antimagic field is active, you can use a bonus action and expend 1 of the armor’s charges to extend its duration until the end of your next turn. The armor regains all expended charges daily at dawn."]
]

var weaponTypes = ["-Select Weapon-", "Dagger", "Shortsword", "Longsword", "Great Axe"]

var weaponEnchantment1 = ["1st Enchantment", ["Ally’s", "1--Ally's--0"], ["Ambushing", "1--Ambushing--0"], ["Answering", "1--Answering-0"], ["Antimagic", "0--Antimagic--0"], ["Arcane", "1--Arcane--0"], ["Athlete’s", "1--Athlete's--0"]]
var weaponEnchantment2 = ["2nd Enchantment", ["Ally’s", "1--Ally's--0"], ["Ambushing", "1--Ambushing--0"], ["Answering", "1--Answering-0"], ["Antimagic", "0--Antimagic--0"], ["Arcane", "1--Arcane--0"], ["Athlete’s", "1--Athlete's--0"]]
var weaponEnchantment3 = ["3rd Enchantment", ["Ally’s", "1--Ally's--0"], ["Ambushing", "1--Ambushing--0"], ["Answering", "1--Answering-0"], ["Antimagic", "0--Antimagic--0"], ["Arcane", "1--Arcane--0"], ["Athlete’s", "1--Athlete's--0"]]

if (event.willCommit) {
  switch (event.value) {
    case "Armor":
      subType.setItems(armorTypes);
      enchantmentType1.setItems(armorEnchantment1);
      enchantmentType2.setItems(armorEnchantment2);
      enchantmentType3.setItems(armorEnchantment3);
      itemName.value = " "
      break;
    case "Weapon":
      subType.setItems(weaponTypes);
      enchantmentType1.setItems(weaponEnchantment1);
      enchantmentType2.setItems(weaponEnchantment2);
      enchantmentType3.setItems(weaponEnchantment3);
      itemName.value = " "
      break;
    default:
      subType.setItems(["-Item Subtype-"]);
      enchantmentType1.setItems(["-1st Enchantment-"])
      enchantmentType2.setItems(["-2nd Enchantment-"])
      enchantmentType3.setItems(["-3rd Enchantment-"])
      itemName.value = " "
      break;
  }
}